services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "99999:25565"
    environment:
      ICON: /server-icon.png
      EULA: "TRUE"
      ONLINE_MODE: false
      TYPE: PAPER
      PAPER_CHANNEL: experimental
      VERSION: 1.21.5

      WHITELIST: |

      
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /mnt/mainstorage/minecraft:/data